### ISSUE TITLE
Lets rename this project to a thing that better represents what it is

### ISSUE THREAD

**Issue by Gozala** [ipfs/js-dag-service#336]
As per https://github.com/ipfs/notes/issues/436 I would love to use ipfs-lite as foundation for IPLD with persistence and (IPFS) network. However I think ipfs-lite is a controversial because it sets up wrong expectations for API (compatibility) and inter-op.

I think it would be a good idea to recognize this as a separate layer in the IPFS stack and give it it's own name & attempt to design best API for the DAG storage & replication without being tied to on that IPFS exposes today.

**Comment by carsonfarmer** [comment]
I am 100% on board with this. It is essentially a DAG Service so something along those lines makes sense. IPDS perhaps? I have not real preferences here, so happy to take suggestions/comments/recommendations from your perspective.

**Comment by Gozala** [comment]
If I recall correctly @mikeal had a suggestion of:

Inter Planetary Dag Persistence (IPDP) 

I have another one:

Inter Planetary Data System (IPDS)

> Or you can swap **Data** with **Dag**

However I'm personally not a big fan of acronyms as they prone to conflicts. And would much rather pick something else here's few 

- DataNet
- DAGNet
- blockscope
- datascope
- blockspan
- dataplot
- blockplot

> I'd like to capture that it represents part of of the larger network of content addressable linked data / blocks.

**Comment by carsonfarmer** [comment]
`DAGPeer` or `PeerDAG` might also work?

**Comment by Gozala** [comment]
I also just tough of `DAGDist` or `BlockDist` this service distributes blocks across the network.

**Comment by lidel** [comment]
No strong favorite on my end, but I agree we should try to come up with something with "DAG" in the name, 
as it automatically sets proper expectations about the abstraction level at which it operates.

`Inter Planetary DAG Service (IPDS)` – boring, but also _really_ clear for folks in our ecosystem
OR write it in a style that indicates its a lower-level plumbing-thing: `dagservice` → `dagserv`

**Comment by mikeal** [comment]
IPDP - Interplanetary Dag Persistence?

**Comment by mikeal** [comment]
hahaha, I had spent so much time reading comments I didn’t see that @Gozala already mentioned this name in the original post, my bad :)

**Comment by Gozala** [comment]
My reading of this thread seems to indicate that `DAGService` or `dagserv` suggested by @lidel is most popular ? If there are no objections, I suggest we pick on of the two and call it a day.

**Comment by mikeal** [comment]
Sorry for the late entry, but I just realized that I’ve been calling the commands I create to put dag’s on the IPFS network as “seed” commands and we hadn’t considered that here yet.

DagSeed? DagSeeder?

**Comment by carsonfarmer** [comment]
While I think DagSeeder is actually pretty representative of what this library ultimately will be, I'm not sure its the right name for an end-user. The seed or seeder language (to me anyway) infers something more akin to pinning or providing. But this library _could_ be used in a "client-only" type mode, where it can fetch but doesn't provide. Service seems like the most robust name, so that's still my vote.

**Comment by mikeal** [comment]
good point, i’m sold.
