### ISSUE TITLE
Migrating this repo to ipfs-shipyard

### ISSUE THREAD

**Issue by Gozala** [ipfs/js-dag-service#337]
We should do #336 before migrating this anywhere _(or maybe it can be part of it, can't remember if you can do the rename)_.

If we want to explore https://github.com/ipfs/notes/issues/436 based on this project I think it would make sense to migrate it (or fork it) into https://github.com/ipfs-shipyard/

Alternatively we could consider creating separate org as both IPLD and IPFS projects have one. I do not personally have strong preferences where to migrate or whether to just iterate over this here, but this did come up multiple times so I think it's best to have discussion here.

**Comment by carsonfarmer** [comment]
I don't think our team has any strong preferences here? Happy to have this live over in ipfs-shipyard or any other PL-based org? Textile is also happy to support development under our org on GitHub, but are also aware that there are always politics to these things that just aren't worth worrying about :)

**Comment by mikeal** [comment]
Why shipyard instead of the main org?

**Comment by lidel** [comment]
I'd move it to `ipfs/` org to give it proper prominence:
this will be important low level plumbing that we expect to be used widely on the web, and possibly in js-ipfs itself at some point.

**Comment by carsonfarmer** [comment]
Sounds good to me
